server:
  port: 8200
spring:
  application:
    name: spring-cloud-config-server
    profiles:
      active: native  # 配置使用本地储存
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/ # 搜索src/main/resource 下的propertie
        git:
          uri: https://github.com/kobezhangali/config-repo.git #配置文件所在仓库
          default-label: main #配置文件分支
          search-paths: config-repo  #配置文件所在根目录										文件夹下的文件
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/